dir: "./keystore/data" ## location of the keystore with wallet's private key
default_network: "calibration"
log_level: "debug"

rpc:
  mainnet:
    address: "https://rpc.ankr.com/filecoin"
    api_token: ""
    chain_id: 314
  calibration:
    address: "https://api.calibration.node.glif.io/rpc/v1"
    api_token: ""
    chain_id: 314159
  localnet:
    address: "http://127.0.0.1:1234/rpc/v1"
    api_token: ""
    chain_id: 31415926

contracts:
  calibration:
    liquid_staking: "0x19AAB7dD96E9EedF9E232fE56d1736f53205834a"
    registry: "0xCc6C40Da237F2311e6D8e8e7832b1f76aA6115E4"
    collateral: "0x98A79c415aF7b4c0c2C8fB440796D02652AbDF87"
  mainnet:
    liquid_staking: "0xd0437765D1Dc0e2fA14E97d290F135eFdf1a8a9A"
    registry: "0x34150FdEd1e598866E5111718e4F5D5af2517f98"
    collateral: "0x3D52874772C66466c93E36cc3782946fd0FA7666"
  localnet:
    liquid_staking: ""
    registry: ""
    collateral: ""

miners:
  mainnet: ["f063869", "f063868"]
  calibration: []
  localnet: []

pledge_timeout: 24 ## number of hours between an auto-pledge operation
